// Router composition root. Mounted at `/api` in src/index.ts.
// Order matters only where handlers overlap; current layout has no overlaps.

import { Router } from 'express';
import health from './health.routes.js';
import authKeys from './auth.routes.js';
import settings from './settings.routes.js';
import catalog from './catalog.routes.js';
import system from './system.routes.js';
import view from './view.routes.js';
import download from './download.routes.js';
import upload from './upload.routes.js';
import mediaLibrary from './mediaLibrary.routes.js';
import history from './history.routes.js';
import gallery from './gallery.routes.js';
import templates from './templates.routes.js';
import templatesImport from './templates.import.js';
import templateWidgets from './templateWidgets.routes.js';
import generate from './generate.routes.js';
import dependencies from './dependencies.routes.js';
import models from './models.routes.js';
import modelsEnrichment from './modelsEnrichment.routes.js';
import modelsRecipes from './modelsRecipes.routes.js';
import civitaiByHash from './civitaiByHash.routes.js';
import comfyuiLifecycle from './comfyui.routes.js';
import comfyuiControl from './comfyui.control.routes.js';
import plugins from './plugins.routes.js';
import python from './python.routes.js';
import civitai from './civitai.routes.js';
import networkConfig from './network.routes.js';
import thumbnail from './thumbnail.routes.js';
import chat from './chat.routes.js';
import chatAttachments from './chat.attachments.routes.js';
import chatModels from './chat.models.routes.js';
import mcp from './mcp.routes.js';
import mcpServers from './mcpServers.routes.js';
import { personalityRouter } from './personality.routes.js';
import videoboard from './videoboard.routes.js';
import characters from './characters.routes.js';
import openapi from './openapi.routes.js';
import gpu from './gpu.routes.js';
import llm from './llm.routes.js';
import jobs from './jobs.routes.js';
import promptRegistry from './promptRegistry.routes.js';
import enhancer from './enhancer.routes.js';

const router = Router();

router.use(health);
router.use(authKeys);
router.use(settings);
router.use(catalog);
router.use(system);
router.use(view);
router.use(download);
router.use(upload);
router.use(mediaLibrary);
router.use(history);
router.use(gallery);
router.use(templates);
router.use(templatesImport);
router.use(templateWidgets);
router.use(generate);
router.use(dependencies);
router.use(models);
router.use(modelsEnrichment);
router.use(modelsRecipes);
router.use(civitaiByHash);
router.use(comfyuiLifecycle);
router.use(comfyuiControl);
router.use(plugins);
router.use(python);
router.use(civitai);
router.use(networkConfig);
router.use(thumbnail);
router.use(chat);
router.use(chatAttachments);
router.use(chatModels);
router.use('/mcp', mcp);          // /api/mcp — Studio's MCP server endpoint
router.use(mcpServers);            // /api/mcp/servers and /api/mcp/profiles
router.use(personalityRouter);
router.use(videoboard);
router.use(characters);
router.use(openapi);
router.use(gpu);
router.use(llm);
router.use(jobs);
router.use(promptRegistry);
router.use(enhancer);

export default router;
