// PNG tEXt/iTXt chunk parser for extracting ComfyUI workflow metadata.
// Ported from artokun's services/image-management.ts (parsing portion only).

interface PngTextChunk { keyword: string; text: string }

function parsePngTextChunks(buffer: Buffer): PngTextChunk[] {
  const results: PngTextChunk[] = [];
  const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (buffer.length < 8 || !buffer.subarray(0, 8).equals(PNG_SIG)) {
    throw new Error('Not a valid PNG file');
  }
  let offset = 8;
  while (offset + 8 <= buffer.length) {
    const chunkLength = buffer.readUInt32BE(offset);
    const chunkType = buffer.subarray(offset + 4, offset + 8).toString('ascii');
    const dataStart = offset + 8;
    const dataEnd = dataStart + chunkLength;
    if (dataEnd > buffer.length) break;

    if (chunkType === 'tEXt') {
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        results.push({
          keyword: data.subarray(0, nullIdx).toString('latin1'),
          text: data.subarray(nullIdx + 1).toString('latin1'),
        });
      }
    } else if (chunkType === 'iTXt') {
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString('utf-8');
        const compressionFlag = data[nullIdx + 1];
        let textStart = nullIdx + 3;
        const langEnd = data.indexOf(0, textStart);
        if (langEnd >= 0) {
          textStart = langEnd + 1;
          const transEnd = data.indexOf(0, textStart);
          if (transEnd >= 0) textStart = transEnd + 1;
        }
        if (compressionFlag === 0) {
          results.push({ keyword, text: data.subarray(textStart).toString('utf-8') });
        }
      }
    }
    if (chunkType === 'IEND') break;
    offset = dataEnd + 4;
  }
  return results;
}

export async function extractWorkflowFromPng(
  buffer: Buffer,
): Promise<{ prompt?: Record<string, unknown>; workflow?: Record<string, unknown> }> {
  const chunks = parsePngTextChunks(buffer);
  const result: { prompt?: Record<string, unknown>; workflow?: Record<string, unknown> } = {};
  for (const { keyword, text } of chunks) {
    if (keyword === 'prompt') {
      try { result.prompt = JSON.parse(text); } catch { /* skip malformed */ }
    } else if (keyword === 'workflow') {
      try { result.workflow = JSON.parse(text); } catch { /* skip malformed */ }
    }
  }
  if (!result.prompt && !result.workflow) {
    throw new Error(
      'No ComfyUI workflow metadata found in this PNG. ' +
      'The image may not have been generated by ComfyUI, or metadata embedding was disabled.',
    );
  }
  return result;
}
