// Video thumbnail extractor + md5 disk cache. Backs `GET /api/gallery/thumbnail`.
//
// The tile grid previously rendered `<video src="/api/view?...">` for every
// video row — the browser pulled MP4 bytes just to paint a poster frame.
// Wave P swaps that for a cached webp poster generated by ffmpeg, so tiles
// ship ~20 KB instead of multi-MB decode work per cell.
//
// Cache layout: `${env.COMFYUI_PATH}/.cache/video-thumbs/<md5>.webp`. Keys
// hash `(path, width)` so a width change invalidates the cache without
// touching older entries. Writes go through a `.tmp` file + atomic rename
// to stop partial files from being served on a race.
//
// ffmpeg-missing path: if the binary isn't on PATH, throw `{ code: 'FFMPEG_MISSING' }`
// so the route can return 404 and the frontend falls through to the
// music-icon gradient / placeholder. Not installed in the image build this
// wave — verification is runtime-only.

import { createHash } from 'crypto';
import {
  existsSync, mkdirSync, renameSync, statSync, unlinkSync,
} from 'fs';
import { spawn } from 'child_process';
import path from 'path';
import { env } from '../config/env.js';

export interface VideoThumbError {
  code: 'FFMPEG_MISSING' | 'FFMPEG_FAILED' | 'INVALID_WIDTH';
  detail?: string;
}

export interface VideoThumbResult {
  filePath: string;
  cached: boolean;
  contentType: string;
}

const MIN_WIDTH = 64;
const MAX_WIDTH = 1024;
const FFMPEG_TIMEOUT_MS = 15_000;

export function isVideoThumbError(err: unknown): err is VideoThumbError {
  if (!err || typeof err !== 'object') return false;
  const code = (err as { code?: unknown }).code;
  return code === 'FFMPEG_MISSING'
    || code === 'FFMPEG_FAILED'
    || code === 'INVALID_WIDTH';
}

function cacheDir(): string {
  return path.join(env.COMFYUI_PATH || '/root/ComfyUI', '.cache', 'video-thumbs');
}

function cacheKey(absPath: string, width: number): string {
  // Include mtime so replacing the file at the same path invalidates the
  // cached thumbnail. Without this, the immutable Cache-Control pin leaves
  // the old webp served forever until the cache dir is manually cleared.
  // A missing file falls through with mtime=0 — the downstream ffmpeg run
  // will error out with FFMPEG_FAILED, which the route maps to a 404.
  let mtime = 0;
  try { mtime = statSync(absPath).mtimeMs; } catch { /* missing */ }
  return createHash('md5').update(`${absPath}|${width}|${mtime}`).digest('hex');
}

function validateWidth(raw: unknown): number {
  if (typeof raw !== 'number' || !Number.isInteger(raw)) {
    throw { code: 'INVALID_WIDTH' } satisfies VideoThumbError;
  }
  if (raw < MIN_WIDTH || raw > MAX_WIDTH) {
    throw { code: 'INVALID_WIDTH' } satisfies VideoThumbError;
  }
  return raw;
}

/**
 * Run `ffmpeg` to grab a single frame ~500ms into the source video, resize
 * to `width`, and write a webp to `finalPath` via `.tmp` + rename. Resolves
 * on success; rejects with a typed `VideoThumbError` on any failure path so
 * the route can map errors onto status codes.
 */
function runFfmpeg(
  srcPath: string, width: number, finalPath: string,
): Promise<void> {
  const tmpPath = `${finalPath}.tmp`;
  // `-f webp` forces the muxer — ffmpeg's auto-detect keys off the output
  // filename extension and our `.webp.tmp` suffix would otherwise fail with
  // "Unable to choose an output format".
  const args = [
    '-hide_banner',
    '-loglevel', 'error',
    '-y',
    // Seek to 0 (first frame). Previously 500ms, but sub-500ms clips
    // (single-frame exports, very-short LoopBack outputs) landed past EOF
    // and wrote a 0-byte webp that the route would then serve as "blank
    // tile forever" via the immutable Cache-Control header.
    '-ss', '0',
    '-i', srcPath,
    '-vframes', '1',
    '-vf', `scale=${width}:-1`,
    '-q:v', '75',
    '-f', 'webp',
    tmpPath,
  ];
  return new Promise<void>((resolve, reject) => {
    let proc;
    try {
      proc = spawn('ffmpeg', args, { stdio: ['ignore', 'ignore', 'pipe'] });
    } catch {
      reject({ code: 'FFMPEG_MISSING' } satisfies VideoThumbError);
      return;
    }
    let stderr = '';
    proc.stderr?.on('data', (b: Buffer) => { stderr += b.toString('utf8'); });
    const timer = setTimeout(() => {
      try { proc.kill('SIGKILL'); } catch { /* ignore */ }
    }, FFMPEG_TIMEOUT_MS);
    proc.on('error', (err: NodeJS.ErrnoException) => {
      clearTimeout(timer);
      try { unlinkSync(tmpPath); } catch { /* ignore */ }
      if (err.code === 'ENOENT') {
        reject({ code: 'FFMPEG_MISSING' } satisfies VideoThumbError);
        return;
      }
      reject({ code: 'FFMPEG_FAILED', detail: err.message } satisfies VideoThumbError);
    });
    proc.on('close', (code: number | null) => {
      clearTimeout(timer);
      if (code === 0) {
        try {
          renameSync(tmpPath, finalPath);
          resolve();
        } catch (err) {
          try { unlinkSync(tmpPath); } catch { /* ignore */ }
          reject({
            code: 'FFMPEG_FAILED',
            detail: err instanceof Error ? err.message : String(err),
          } satisfies VideoThumbError);
        }
        return;
      }
      try { unlinkSync(tmpPath); } catch { /* ignore */ }
      reject({
        code: 'FFMPEG_FAILED',
        detail: stderr.trim() || `ffmpeg exit ${code}`,
      } satisfies VideoThumbError);
    });
  });
}

export interface ThumbArgs {
  absPath: string;
  width: number;
}

/**
 * Resolve a cached webp thumbnail for `absPath` at `width`, generating it
 * via ffmpeg on miss. Returns the cache-file path + an `image/webp`
 * content-type the caller can stream.
 */
export async function thumbnailForVideo(
  args: ThumbArgs,
): Promise<VideoThumbResult> {
  const width = validateWidth(args.width);
  const dir = cacheDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const key = cacheKey(args.absPath, width);
  const filePath = path.join(dir, `${key}.webp`);
  const contentType = 'image/webp';

  if (existsSync(filePath)) {
    try {
      if (statSync(filePath).size > 0) {
        return { filePath, cached: true, contentType };
      }
    } catch { /* fall through to miss path */ }
  }

  await runFfmpeg(args.absPath, width, filePath);
  return { filePath, cached: false, contentType };
}
